name: Run Collector Python script

on:
    schedule:
        - cron: "50 2 * * *"
    workflow_dispatch: # 수동 트리거

jobs:
    run-script:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  ref: main

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.12"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install requests beautifulsoup4

            - name: Configure Git
              run: |
                  git config --global user.name 'ko-hoon'
                  git config --global user.email 'seunghoon_jeon@kolon.com'

            - name: Run Python script
              env:
                  KOREA_BANK_API_KEY: ${{ secrets.KOREA_BANK_API_KEY }}
                  OPINET_API_KEY: ${{ secrets.OPINET_API_KEY }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  PUBLIC_DATA_CENTER_API_KEY: ${{ secrets.PUBLIC_DATA_CENTER_API_KEY }}
                  LME_PRICE_BOARD_URL: ${{ secrets.LME_PRICE_BOARD_URL }}
                  LME_PRICE_LIST_URL: ${{ secrets.LME_PRICE_LIST_URL }}
              run: python collector.py

            - name: Check for changes
              id: git-status
              run: |
                  git add .
                  echo "::set-output name=changes::$(git status --porcelain)"

            - name: Commit and push if changes
              if: steps.git-status.outputs.changes != ''
              run: |
                  git commit -m "Update data from collector script [skip ci]"
                  git push
